[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[free-wb]
source = "cmd"
cmd = "curl -s https://d.store.deepinos.org.cn///store/tools/freewb/app.json  | jq -r '.Version'"

[netease-cloud-music-gtk4]
source = "github"
github = "gmg137/netease-cloud-music-gtk"
use_latest_release = true

[aliyundrive-webdav]
source = "github"
github = "messense/aliyundrive-webdav"
use_latest_release = true
